// Sequential scope trip-wire: proves that everything changed since the task's
// base commit is inside that task's declared `Files:` set in .codex-flow/TASKS.md.
// Sequential runs have no worktree boundary, so an executor can silently edit a
// file the task never declared; this helper makes that mechanical instead of
// relying on prose review.
//
// Usage: node scripts/scope-check.mjs --task T<n> --base <sha> [--tasks <path>]
//   default tasks file: .codex-flow/TASKS.md
// Exit codes: 0 = no extra paths; 1 = placeholder/empty `Files:` or one or more
// extra paths (each printed); 2 = usage, file, or git invocation failure.

import { execFileSync } from 'node:child_process'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

export const DEFAULT_TASKS_PATH = path.join('.codex-flow', 'TASKS.md')

// Generated by package managers, never authored by a task.
export const EXCLUDED_LOCKFILES = Object.freeze([
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'bun.lockb',
])
// Installed by a package manager at any depth, never authored by a task. A parallel
// worktree also carries a `node_modules` symlink that git reports as untracked, which
// would otherwise trip the wire on every worktree run. Matched by basename, so files
// *inside* a dependency tree still count (git ignores them anyway).
export const EXCLUDED_DEPENDENCY_DIRECTORIES = Object.freeze(['node_modules'])
// The flow's own control artifacts are written by the coordinator, not the task.
export const EXCLUDED_DIRECTORY = '.codex-flow'

export const EXIT_OK = 0
export const EXIT_VIOLATION = 1
export const EXIT_FAILURE = 2

const USAGE = 'usage: node scripts/scope-check.mjs --task T<n> --base <sha> [--tasks <path>]'
const TASK_ID = /^T\d+$/i
const TASK_HEADER = /^##\s+(T\d+):\s*(.*)$/i
const ANY_HEADER = /^##\s+/
const FILES_FIELD = /^\s*-\s*Files:\s*(.*)$/i
const GIT_OBJECT_NAME = /^[0-9a-fA-F]{4,64}$/
// Only these two platforms fold case in practice; treating Linux paths as
// case-insensitive would hide a genuinely different file.
const CASE_INSENSITIVE_PLATFORMS = new Set(['darwin', 'win32'])
// Tokens a plan author leaves behind when the file list is not filled in yet.
const PLACEHOLDER_TOKENS = new Set(['—', '–', '-', 'none', 'n/a', 'tbd'])

/** Raised when a task's `Files:` declaration cannot be trusted (empty, placeholder, missing task). */
export class ScopeDeclarationError extends Error {
  constructor(message) {
    super(message)
    this.name = 'ScopeDeclarationError'
  }
}

/** Raised on bad CLI arguments; mapped to exit 2. */
class UsageError extends Error {
  constructor(message) {
    super(message)
    this.name = 'UsageError'
  }
}

const errorMessage = (error) =>
  (error instanceof Error ? error.message : String(error)).replace(/\s+/g, ' ').trim()

const isPlaceholderToken = (token) =>
  token.includes('<') || token.includes('>') || PLACEHOLDER_TOKENS.has(token.toLowerCase())

/**
 * Normalize one path for comparison: drop `.` segments and repeated separators, keep a
 * leading `/` so an absolute path never folds onto a relative declaration, and fold case
 * on case-insensitive platforms. On win32 only, `\` is also a separator.
 *
 * Deliberately does NOT trim, does NOT rewrite `\` off win32, and does NOT resolve `..`:
 * on POSIX a leading space and a backslash are legal filename characters, and a `..`
 * segment cannot be resolved without knowing the real tree, so folding any of them here
 * would let a real file named `src\secret.ts`, ` secret.ts`, or `src/../secret.ts`
 * canonicalize onto a declared path and slip past the trip-wire. That is why this
 * function is NOT identical to `canonicalPath` in scripts/task-waves.mjs, which
 * canonicalizes plan-authored declarations (where collapsing is the safe direction)
 * rather than paths git reports. Declared `Files:` tokens are already whitespace-free
 * because they come from a comma/space split. Local on purpose so the helper stays
 * independently runnable.
 */
export function canonicalPath(filePath, platform = process.platform) {
  if (typeof filePath !== 'string') throw new TypeError('filePath must be a string')
  const withSlashes = platform === 'win32' ? filePath.replaceAll('\\', '/') : filePath
  const segments = withSlashes.split('/').filter((segment) => segment !== '' && segment !== '.')
  const joined = segments.join('/')
  const rooted = withSlashes.startsWith('/') ? `/${joined}` : joined
  return CASE_INSENSITIVE_PLATFORMS.has(platform) ? rooted.toLowerCase() : rooted
}

/** True for the generated lockfiles, any `node_modules` entry, and every `.codex-flow/**` path. */
export function isExcludedPath(canonicalized) {
  if (typeof canonicalized !== 'string' || canonicalized === '') return false
  const basename = canonicalized.slice(canonicalized.lastIndexOf('/') + 1)
  if (EXCLUDED_LOCKFILES.includes(basename)) return true
  if (EXCLUDED_DEPENDENCY_DIRECTORIES.includes(basename)) return true
  return canonicalized === EXCLUDED_DIRECTORY || canonicalized.startsWith(`${EXCLUDED_DIRECTORY}/`)
}

/**
 * Read one task's `Files:` declaration out of a TASKS.md body (CRLF safe).
 * Returns { id, title, declaration } or null when the task has no header.
 */
export function parseTaskFilesField(tasksText, taskId) {
  if (typeof tasksText !== 'string') throw new TypeError('tasksText must be a string')
  if (typeof taskId !== 'string' || !TASK_ID.test(taskId)) {
    throw new TypeError('taskId must look like T<n>')
  }
  const wanted = taskId.toUpperCase()
  let isInsideTask = false
  let task = null

  for (const line of tasksText.split(/\r?\n/)) {
    const header = line.match(TASK_HEADER)
    if (header) {
      // Any later `##` header ends the task's scope, so a bullet in a following
      // section cannot overwrite the declaration (same guard as task-waves.mjs).
      if (isInsideTask) return task
      isInsideTask = header[1].toUpperCase() === wanted
      if (isInsideTask) task = { id: wanted, title: header[2].trim(), declaration: null }
      continue
    }
    if (ANY_HEADER.test(line)) {
      if (isInsideTask) return task
      continue
    }
    if (!isInsideTask || task.declaration !== null) continue
    const files = line.match(FILES_FIELD)
    if (files) task = { ...task, declaration: files[1].trim() }
  }
  return task
}

/**
 * Pure comparison of a task's declared files against the changed paths.
 * Returns { allowed, changed, extras }: `allowed` and `changed` are canonical (the
 * comparison basis), while `extras` keeps each path's ORIGINAL spelling as git
 * reported it, so the printed violation is a path the operator can act on. Throws
 * ScopeDeclarationError when the declaration is missing, empty, or a placeholder.
 */
export function scopeCheck(taskId, base, tasksText, changedPaths, platform = process.platform) {
  if (typeof taskId !== 'string' || !TASK_ID.test(taskId)) {
    throw new TypeError('taskId must look like T<n>')
  }
  if (typeof base !== 'string' || !base.trim()) throw new TypeError('base must be a non-empty string')
  if (!Array.isArray(changedPaths) || changedPaths.some((entry) => typeof entry !== 'string')) {
    throw new TypeError('changedPaths must be an array of strings')
  }

  const id = taskId.toUpperCase()
  const task = parseTaskFilesField(tasksText, id)
  if (task === null) throw new ScopeDeclarationError(`${id} not found in the tasks file`)
  if (task.declaration === null || task.declaration === '') {
    throw new ScopeDeclarationError(
      `${id} declares an empty Files: field — refusing to treat "no files" as "everything allowed"`,
    )
  }

  const tokens = task.declaration.split(/[,\s]+/).filter(Boolean)
  const placeholders = tokens.filter(isPlaceholderToken)
  if (tokens.length === 0 || placeholders.length > 0) {
    throw new ScopeDeclarationError(
      `${id} has a placeholder Files: field (${task.declaration}) — refusing to treat "no files" as "everything allowed"`,
    )
  }

  const allowed = [...new Set(tokens.map((token) => canonicalPath(token, platform)))].sort()
  const allowedSet = new Set(allowed)
  // Comparison stays canonical, but an operator needs the spelling git reported to
  // open or `git checkout` the file, so remember the first original per canonical form.
  const originalByCanonical = new Map()
  for (const entry of changedPaths) {
    const canonicalized = canonicalPath(entry, platform)
    if (!canonicalized || originalByCanonical.has(canonicalized)) continue
    originalByCanonical.set(canonicalized, entry)
  }
  const changed = [...originalByCanonical.keys()].sort()
  const extras = changed
    .filter((entry) => !allowedSet.has(entry) && !isExcludedPath(entry))
    .map((entry) => originalByCanonical.get(entry))
  return { allowed, changed, extras }
}

/** Run one git command rooted at cwd and split its NUL-separated path output. */
function gitPaths(args, cwd) {
  const output = execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  return output.split('\0').filter(Boolean)
}

/** Tracked changes since base plus untracked, non-ignored files. Throws on git failure. */
export function collectChangedPaths(base, cwd = process.cwd()) {
  if (typeof base !== 'string' || !GIT_OBJECT_NAME.test(base)) {
    throw new TypeError(`base must be a git object name (got: ${base})`)
  }
  return [
    ...gitPaths(['diff', '--name-only', '-z', base], cwd),
    ...gitPaths(['ls-files', '-z', '--others', '--exclude-standard'], cwd),
  ]
}

/**
 * Parse `--task T<n> --base <sha> [--tasks <path>]`. Throws UsageError on anything else,
 * including a repeated flag: silently letting the last one win would make
 * `--base <right sha> --base <wrong sha>` compare against a base the operator never meant.
 */
export function parseCliArgs(argv) {
  if (!Array.isArray(argv)) throw new TypeError('argv must be an array')
  const flags = { '--task': 'task', '--base': 'base', '--tasks': 'tasks' }
  const parsed = { task: '', base: '', tasks: DEFAULT_TASKS_PATH }
  const seenFlags = new Set()

  for (let index = 0; index < argv.length; index += 1) {
    const flag = argv[index]
    const key = flags[flag]
    if (!key) throw new UsageError(`unknown argument ${flag}`)
    if (seenFlags.has(flag)) throw new UsageError(`duplicate argument ${flag}`)
    seenFlags.add(flag)
    const value = argv[index + 1]
    if (value === undefined || value.startsWith('--')) {
      throw new UsageError(`${flag} requires a value`)
    }
    parsed[key] = value.trim()
    index += 1
  }

  if (!TASK_ID.test(parsed.task)) {
    throw new UsageError(`--task requires a task id like T3 (got: ${parsed.task || '<missing>'})`)
  }
  if (!GIT_OBJECT_NAME.test(parsed.base)) {
    throw new UsageError(`--base requires a git object name (got: ${parsed.base || '<missing>'})`)
  }
  if (!parsed.tasks) throw new UsageError('--tasks requires a path')
  return Object.freeze({ ...parsed, task: parsed.task.toUpperCase() })
}

/** CLI entry point. Resolves to the process exit code; never throws for expected failures. */
export async function main(argv = process.argv.slice(2), { cwd = process.cwd() } = {}) {
  if (typeof cwd !== 'string' || !cwd.trim()) throw new TypeError('cwd must be a non-empty string')

  let config
  try {
    config = parseCliArgs(argv)
  } catch (error) {
    console.error(`scope-check: ${errorMessage(error)}`)
    console.error(USAGE)
    return EXIT_FAILURE
  }

  let tasksText
  const tasksPath = path.resolve(cwd, config.tasks)
  try {
    tasksText = await fs.readFile(tasksPath, 'utf8')
  } catch (error) {
    console.error(`scope-check: cannot read tasks file ${tasksPath}: ${errorMessage(error)}`)
    return EXIT_FAILURE
  }

  let changedPaths
  try {
    changedPaths = collectChangedPaths(config.base, cwd)
  } catch (error) {
    console.error(`scope-check: git failed for base ${config.base}: ${errorMessage(error)}`)
    return EXIT_FAILURE
  }

  let result
  try {
    result = scopeCheck(config.task, config.base, tasksText, changedPaths)
  } catch (error) {
    if (error instanceof ScopeDeclarationError) {
      console.error(`scope-check: ${errorMessage(error)}`)
      return EXIT_VIOLATION
    }
    throw error
  }

  if (result.extras.length > 0) {
    console.error(
      `scope-check: ${config.task}: ${result.extras.length} path(s) outside the declared Files: (base ${config.base})`,
    )
    for (const extra of result.extras) console.error(`  extra: ${extra}`)
    return EXIT_VIOLATION
  }

  console.log(
    `scope-check: ${config.task}: ${result.changed.length} changed path(s), all within Files: (base ${config.base})`,
  )
  return EXIT_OK
}

const isDirectRun =
  process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href

if (isDirectRun) {
  main()
    .then((exitCode) => {
      process.exitCode = exitCode
    })
    .catch((error) => {
      console.error(`scope-check: ${errorMessage(error)}`)
      process.exitCode = EXIT_FAILURE
    })
}
